# Generated by Django 2.1.7 on 2019-02-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='提案标题')),
                ('comment', models.TextField(max_length=256, verbose_name='提案更改内容说明')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('assigner', models.CharField(max_length=64, verbose_name='上线审核人')),
                ('newest_version', models.IntegerField(default=0, verbose_name='将要上线的最新版本')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提案创建时间')),
                ('last_mtime', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('status', models.IntegerField(default=1, verbose_name='提案状态')),
                ('diff', models.TextField(blank=True, null=True)),
                ('timeline', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品名称')),
            ],
            options={
                'db_table': 'issue',
                'ordering': ['pk'],
            },
        ),
    ]
