# Generated by Django 2.1.7 on 2019-03-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='diff',
            field=models.TextField(blank=True, null=True, verbose_name='上线差异部分'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timeline',
            field=models.TextField(blank=True, null=True, verbose_name='时间线信息'),
        ),
    ]
