# Generated by Django 2.0.13 on 2019-03-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20190301_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='diff',
            field=models.TextField(blank=True, default='', null=True, verbose_name='上线差异部分'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timeline',
            field=models.TextField(blank=True, default='', null=True, verbose_name='时间线信息'),
        ),
    ]
