# Generated by Django 2.0.13 on 2019-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20190305_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='message',
        ),
        migrations.AddField(
            model_name='issue',
            name='diff_change',
            field=models.TextField(blank=True, default='', null=True, verbose_name='改变信息'),
        ),
        migrations.AddField(
            model_name='issue',
            name='diff_delete',
            field=models.TextField(blank=True, default='', null=True, verbose_name='删除信息'),
        ),
        migrations.AddField(
            model_name='issue',
            name='diff_new',
            field=models.TextField(blank=True, default='', null=True, verbose_name='新增信息'),
        ),
    ]
