# Generated by Django 2.0.13 on 2019-03-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20190307_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='diff_change',
            field=models.TextField(blank=True, default='', null=True, verbose_name='变化的文件和文件夹'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='diff_delete',
            field=models.TextField(blank=True, default='', null=True, verbose_name='删除的文件和文件夹'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='diff_new',
            field=models.TextField(blank=True, default='', null=True, verbose_name='新增的文件和文件夹'),
        ),
    ]
