# Generated by Django 2.0.13 on 2019-03-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20190308_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='fail_ip',
            field=models.TextField(blank=True, null=True, verbose_name='上线失败IP'),
        ),
        migrations.AddField(
            model_name='issue',
            name='success_ip',
            field=models.TextField(blank=True, null=True, verbose_name='上线成功IP'),
        ),
    ]
