# Generated by Django 2.0.13 on 2019-03-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_auto_20190308_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fail_ip',
            field=models.TextField(blank=True, default='', null=True, verbose_name='上线失败IP'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='success_ip',
            field=models.TextField(blank=True, default='', null=True, verbose_name='上线成功IP'),
        ),
    ]
