# Generated by Django 2.1.7 on 2019-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='domain',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='产品域名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_sync_file_and_path',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='不同步的文件或者目录换行分割'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sync_type',
            field=models.CharField(choices=[('t', '测试'), ('g', '灰度'), ('o', '线上'), ('tg', '测试+灰度'), ('to', '测试+线上'), ('go', '灰度+线上'), ('tgo', '测试+灰度+线上')], max_length=20, verbose_name='上线选项_测试or灰度or线上'),
        ),
    ]
