# Generated by Django 2.1.7 on 2019-02-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190227_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='project_dir',
            field=models.CharField(max_length=128, unique=True, verbose_name='线上代码目录'),
        ),
    ]
