# Generated by Django 2.1.7 on 2019-02-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190228_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='project_dir',
            new_name='product_dir',
        ),
        migrations.AlterField(
            model_name='product',
            name='sync_option',
            field=models.CharField(choices=[('incremental', '增量上线'), ('full', '全量上线')], max_length=64, verbose_name='上线选项_全量or增量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sync_type',
            field=models.CharField(choices=[('t', '测试'), ('g', '灰度'), ('o', '线上'), ('tg', '测试+灰度'), ('to', '测试+线上'), ('go', '灰度+线上'), ('tgo', '测试+灰度+线上')], max_length=20, verbose_name='上线类型_测试or灰度or线上'),
        ),
    ]
