# Generated by Django 2.1.7 on 2019-03-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190228_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gray_ip_list',
            field=models.TextField(blank=True, help_text='逗号分割', max_length=500, null=True, verbose_name='灰度机器地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='online_ip_list',
            field=models.TextField(blank=True, help_text='逗号分割', max_length=500, null=True, verbose_name='上线机器地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='test_ip_list',
            field=models.TextField(blank=True, help_text='逗号分割', max_length=500, null=True, verbose_name='测试机器地址'),
        ),
    ]
