# Generated by Django 2.0.13 on 2019-03-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190301_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='git_path',
            new_name='git_address',
        ),
    ]
