# Generated by Django 2.1.7 on 2019-03-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190227_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_sa',
            field=models.BooleanField(default=False, verbose_name='是否是sa'),
        ),
    ]
